name: PR Check

on:
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Lint and Test (Node.js ${{ matrix.node-version }})
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20, 22]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Run Linter
              run: npm run lint

            - name: Run Tests with Coverage
              run: |
                  npm run test -- --coverage --coverage.reporter=text-summary > coverage-${{ matrix.node-version }}.txt
                  cat coverage-${{ matrix.node-version }}.txt

            - name: Comment PR with coverage summary
              if: matrix.node-version == 22 # Only post one comment, from the latest node version
              uses: thollander/actions-comment-pull-request@v3
              with:
                  file-path: coverage-22.txt
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
